# Generated by Django 4.2.1 on 2023-06-02 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('partido', models.CharField(default=None, max_length=50)),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('ementa', models.CharField(max_length=2000)),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Atualização')),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='autor_projeto', to='cadastro.deputado')),
            ],
            options={
                'ordering': ['-ano', '-numero'],
                'unique_together': {('ano', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='TipoReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default=None, max_length=10)),
                ('descricao', models.CharField(default=None, max_length=100)),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tramitacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Tramitação')),
                ('tem_parecer', models.BooleanField(default=False)),
                ('reuniao', models.IntegerField(default=None)),
                ('observacao', models.CharField(default=None, max_length=2000)),
                ('esta_na_comissao', models.BooleanField(default=True)),
                ('parecer_notes', models.BooleanField(default=False)),
                ('numero_lei', models.CharField(blank=None, max_length=50, null=True)),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Atualização')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.comissao')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.projeto')),
                ('relator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relator_projeto', to='cadastro.deputado')),
            ],
            options={
                'ordering': ['-data_tramitacao'],
            },
        ),
        migrations.CreateModel(
            name='ControleReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=None)),
                ('data_reuniao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Reunião')),
                ('tem_edital_assinado', models.BooleanField(default=False)),
                ('data_edital_do', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Edital D.O.')),
                ('tem_presenca_assinada', models.BooleanField(default=False)),
                ('tem_ata_assinada', models.BooleanField(default=False)),
                ('data_ata_do', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Ata D.O.')),
                ('tem_parecer', models.BooleanField(default=False)),
                ('tem_parecer_assinado', models.BooleanField(default=False)),
                ('tem_deliberacao', models.BooleanField(default=False)),
                ('tem_deliberacao_assinada', models.BooleanField(default=False)),
                ('tem_conclusao', models.BooleanField(default=False)),
                ('tem_conclusao_assinada', models.BooleanField(default=False)),
                ('observacao', models.TextField()),
                ('concluido', models.BooleanField(default=False)),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Atualização')),
                ('tiporeuniao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.tiporeuniao')),
            ],
        ),
    ]
