# Generated by Django 5.0.6 on 2025-07-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='observacao',
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='observacao',
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
    ]
