# Generated by Django 4.2.1 on 2023-06-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_controlereuniao_data_parecer_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlereuniao',
            name='tem_ata_assinada',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NA', 'N/A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlereuniao',
            name='tem_conclusao',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NA', 'N/A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlereuniao',
            name='tem_conclusao_assinada',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NA', 'N/A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlereuniao',
            name='tem_deliberacao',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NA', 'N/A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlereuniao',
            name='tem_deliberacao_assinada',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NA', 'N/A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlereuniao',
            name='tem_edital_assinado',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NA', 'N/A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlereuniao',
            name='tem_parecer',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NA', 'N/A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlereuniao',
            name='tem_parecer_assinado',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NA', 'N/A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='controlereuniao',
            name='tem_presenca_assinada',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('NA', 'N/A')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='esta_na_comissao',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='parecer_notes',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1),
        ),
    ]
