# Generated by Django 5.0.6 on 2025-07-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_projeto_observacao_alter_tramitacao_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='observacao',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='observacao',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
