# Generated by Django 5.0.6 on 2025-07-26 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_projeto_observacao_alter_tramitacao_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='esta_na_comissao',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='parecer_notes',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='reuniao',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tem_parecer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='comissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.comissao'),
        ),
    ]
